spring:
  profiles:
    default: pt-BR
---
spring:
  config:
    activate:
      on-profile:
      - pt-BR
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile:
      - es-AR
  redis:
    database: 0
    host: localhost
    port: 16379
    password: mypass
    timeout: 60000
